import type { Metadata } from "next";
import "@/app/globals.css";
import { redirect } from "next/navigation";

import { cookies } from "next/headers";
export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};
export default async function LayoutRoot({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesSesion = await cookies();
  const session = cookiesSesion.get("bearer-token");
  if (!session) {
    redirect("/login");
  }
  return (
    <html lang="es">
      <body >
        <main>{children}</main>
      </body>
    </html>
  );
}
