import type { Metadata } from "next";
import "@/app/globals.css";
import { Toast } from "./dashboard/components/Toast";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};
export default async function LayoutRoot({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <Toast />
        <main>{children}</main>
      </body>
    </html>
  );
}
