import Aside from "./components/Aside";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookiesSesion = await cookies();
  const session = cookiesSesion.get("bearer-token")?.value;
  if (!session) {
    redirect("/login");
  }

  return (
    <main className="flex flex-col sm:flex-row min-h-screen ">
      <Aside />
      <div className="sm:ml-64 bg-[#eeeeee] w-full">{children}</div>
    </main>
  );
}
